# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CompareResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, score: float=None, diff_image: str=None):  # noqa: E501
        """CompareResponse - a model defined in Swagger

        :param score: The score of this CompareResponse.  # noqa: E501
        :type score: float
        :param diff_image: The diff_image of this CompareResponse.  # noqa: E501
        :type diff_image: str
        """
        self.swagger_types = {
            'score': float,
            'diff_image': str
        }

        self.attribute_map = {
            'score': 'score',
            'diff_image': 'diff_image'
        }
        self._score = score
        self._diff_image = diff_image

    @classmethod
    def from_dict(cls, dikt) -> 'CompareResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CompareResponse of this CompareResponse.  # noqa: E501
        :rtype: CompareResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def score(self) -> float:
        """Gets the score of this CompareResponse.


        :return: The score of this CompareResponse.
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score: float):
        """Sets the score of this CompareResponse.


        :param score: The score of this CompareResponse.
        :type score: float
        """
        if score is None:
            raise ValueError("Invalid value for `score`, must not be `None`")  # noqa: E501

        self._score = score

    @property
    def diff_image(self) -> str:
        """Gets the diff_image of this CompareResponse.


        :return: The diff_image of this CompareResponse.
        :rtype: str
        """
        return self._diff_image

    @diff_image.setter
    def diff_image(self, diff_image: str):
        """Sets the diff_image of this CompareResponse.


        :param diff_image: The diff_image of this CompareResponse.
        :type diff_image: str
        """
        if diff_image is None:
            raise ValueError("Invalid value for `diff_image`, must not be `None`")  # noqa: E501

        self._diff_image = diff_image
