openapi: 3.0.0
info:
  title: Screenshot maker
  description: Allows to take screenshots of provided URLs (maybe render HTML in the
    future)
  contact:
    email: darthtyranus666666@gmail.com
  license:
    name: MIT
  version: 1.0.0
servers:
- url: /v1
  description: first api version
paths:
  /screenshot:
    get:
      summary: gets screenshot of provided URL
      operationId: screenshot
      parameters:
      - name: url
        in: query
        description: URL of the page you want to take a screenshot of
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        200:
          description: successful screenshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Screenshot'
        400:
          description: bad input parameters
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /live:
    get:
      tags: [Liveness]
      summary: Liveness Check
      operationId: live
      responses:
        '200':
          description: Status message from server describing current liveness
      x-openapi-router-controller: swagger_server.controllers.health_controller
  /ready:
    get:
      tags: [Readiness]
      summary: Readiness Check
      operationId: ready
      responses:
        '200':
          description: Status message from server describing current liveness
      x-openapi-router-controller: swagger_server.controllers.health_controller
components:
  schemas:
    Screenshot:
      required:
      - image
      type: object
      properties:
        image:
          type: string
          example: base64 encoded png
      example:
        image: base64 encoded png

