Resources:
  DynamoDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: user_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  DynamoDBName:
    Value:
      Ref: DynamoDB
