/*
 * Manager
 *
 * Main control point of monitoring. Creates new deployments, keeps info about current ones etc.
 *
 * API version: 1.0.0
 * Contact: darthtyranus666666@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"strconv"
	"strings"
	"time"

	"github.com/dezeroku/monitor-page/manager/v2/auth"
)

// Item desribes single monitoring job.
type Item struct {
	ID        uint       `gorm:"primary_key" json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`

	URL string `json:"url" gorm:"not null"`

	SleepTime int32 `json:"sleepTime" gorm:"not null"`

	MakeScreenshots bool `json:"makeScreenshots" gorm:"not null"`

	Owner     string    `json:"owner" gorm:"not null"`
	RealOwner auth.User `json:"-" gorm:"foreignkey:Owner"`
}

func (i *Item) GetDeploymentName() string {
	// Make sure that DeploymentName is deterministic and does not contain any info that may change when updating.
	temp := strings.ToLower(i.URL) + "-" + strconv.Itoa(int(i.ID)) + "-" + i.CreatedAt.Format("2006-01-02-15-04-05") + "-" + strings.ToLower(i.Owner)
	temp = strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(temp, "@", "at"), ":", "-"), "/", "-"), "#", "-"), "_", "-"), "=", "-"), "?", "-")
	return temp
}
