/*
 * Manager
 *
 * Main control point of monitoring. Creates new deployments, keeps info about current ones etc.
 *
 * API version: 1.0.0
 * Contact: darthtyranus666666@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body struct {

	Email string `json:"email"`

	RedirectUri string `json:"redirectUri"`
}
