/*
 * Manager
 *
 * Main control point of monitoring. Creates new deployments, keeps info about current ones etc.
 *
 * API version: 1.0.0
 * Contact: darthtyranus666666@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ItemWithId is just json abstraction over normal Item.
// It's kept in DB as Item (all of these have IDs by default).
type ItemWithId struct {
	Url string `json:"url"`

	SleepTime int32 `json:"sleepTime"`

	MakeScreenshots bool `json:"makeScreenshots"`

	Owner string `json:"owner"`

	Id int32 `json:"id"`
}
