#!/usr/bin/env bash
set -euo pipefail

RUNDIR="$(readlink -f "$(dirname "$0")")"
cd "${RUNDIR}"

pushd builder

if [[ "${GHA_DOCKER_CACHING:-false}" == "true" ]]; then
    EXTRA_ARGS="--cache-to type=gha,mode=max --cache-from type=gha"
fi

# Handle proper IDs during a build, so permissions are OK on host
# shellcheck disable=SC2086 # Intended globbing
docker buildx build . --build-arg UID="$(id -u)" --build-arg GID="$(id -u)" -t diagrams-builder ${EXTRA_ARGS:-}
popd

docker run -v "$PWD:/diagrams" -it diagrams-builder /bin/sh -c 'cd /diagrams; for x in $(ls *.py); do python $x; done;'

mkdir -p created

mv ./*.png created
