---
name: Run pre-commit checks

on:
  push:

  workflow_dispatch:

  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install and run pre-commit
        run: |
          pipx install pre-commit
          pre-commit run --all-files
